steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/tech-rnd-project/hello-world:latest", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/tech-rnd-project/hello-world:latest"]
  
- id: 'create-attestation'
  name: 'gcr.io/tech-rnd-project/binauthz-attestation:latest'
  args:
    - '--artifact-url'
    - 'us-central1-docker.pkg.dev/tech-rnd-project/cloud-run-source-deploy/mydashboard:latest'
    - '--attestor'
    - 'projects/tech-rnd-project/attestors/my-binauthz-attestor'
    - '--keyversion'
    - 'projects/tech-rnd-project/locations/global/keyRings/binauthz-keys/cryptoKeys/codelab-key/cryptoKeyVersions/1'
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --image=gcr.io/tech-rnd-project/hello-world:latest
  - --location=us-central1-a
  - --cluster=cluster-1
